apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- servicemonitorresource.yaml
- service.yaml
patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --enable-metrics=true
      - op: add
        path: /spec/template/spec/containers/0/ports/-
        value:
          containerPort: 8080
          name: http-metrics
          protocol: TCP
    target:
      kind: Deployment
      name: "(source-controller|kustomize-controller|helm-controller|notification-controller)"
