apiVersion: v1
kind: Service
metadata:
  name: flux-metrics
  namespace: flux-system
  labels:
    app: flux
spec:
  selector:
    app.kubernetes.io/name: source-controller
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
