apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- grafana_deployment.yaml
- grafana_service.yaml
- promethues_deployment.yaml
- promethues_service.yaml
- promethues_configmap.yaml
- nodeexporter_deployment.yaml
- nodeexporter_service.yaml
- cadvisor.yaml