apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafana_deployment.yaml
- grafana_service.yaml
- prometheus_deployment.yaml
- prometheus_service.yaml
- prometheus_configmap.yaml
- nodexporter_deployment.yaml
- nodexporter_service.yaml
- cadvisor.yaml