apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafana_deployment.yaml
- grafana_service.yaml
- promethues_deployment.yaml
- promethues_service.yaml
- promethues_configmap.yaml
- nodexporter_deployment.yaml
- nodexporter_service.yaml
- cadvisor.yaml