apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
data:
  promethues_configmap.yaml: |
    global:
      scrape_interval: 15s
        #evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 5s
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']
            #- job_name: 'tempo-metrics'
            #metrics_path: '/metrics'
            #static_configs:
            #- targets: ['tempo.tempons.svc.cluster.local:3200']
      - job_name: 'flux'
        static_configs:
          - targets: ['source-controller.flux-system.svc.cluster.local:9090']
      - job_name: 'minio'
    # Use Kubernetes service discovery to find MinIO endpoints
        kubernetes_sd_configs:
          - role: endpoints  # Discover endpoints associated with the Service
            namespaces:
              names:
                - minio  # Namespace where MinIO is deployed

    # Relabeling to filter and configure the scrape target
        relabel_configs:
      # Keep only endpoints with the MinIO Service label
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: my-minio-fs  # Match the label of your MinIO Service

      # Use the Service name as the job instance
          - source_labels: [__meta_kubernetes_service_name]
            target_label: job

      # Use the MinIO metrics path
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
            replacement: /minio/v2/metrics/cluster  # MinIO metrics endpoint

      # Use the MinIO metrics port
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: (.+)
            replacement: $1:9000

            #- job_name: 'minio'
        #static_configs:

          #- targets: ['my-minio-fs-service.minio.svc.cluster.local:9000']
            #- job_name: 'myapp1'
        #static_configs:
          #- targets: ['tempo.tempons.svc.cluster.local:4318']

            #- job_name: 'myapp'
            #static_configs:
            #- targets: ['tempo.tempons.svc.cluster.local:4317']
            #- job_name: 'kubernetes-pods'

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\\d+)?;(\\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)

      - job_name: cadvisor
        scrape_interval: 5s
        static_configs:
        - targets: ['cadvisor:8080']